const SEARCH_VALUE = "SEARCH_VALUE";
const ISLOADING = "IS_LOADING";
const SEARCH_RESPONSE = "SEARCH_RESPONSE";
const ADD_BOOKMARK ="ADD_BOOKMARK";
const REMOVE_BOOKMARK = "REMOVE_BOOKMARK";
const POKEMON_DETAILS="POKEMON_DETAILS";



export { SEARCH_VALUE,ISLOADING ,SEARCH_RESPONSE,ADD_BOOKMARK,REMOVE_BOOKMARK,POKEMON_DETAILS}